name: Release Frontend

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image with Buildx
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE=${IMAGE,,}  # lowercase
          docker buildx build \
            --tag $IMAGE:${{ env.version }} \
            --tag $IMAGE:latest \
            --push \
            .
